name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Kiểm tra mã nguồn từ kho GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Cài đặt JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # Đảm bảo không có khoảng trắng thừa

    # Lưu cache phụ thuộc Maven để tăng tốc độ build
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Build với Maven
    - name: Build with Maven
      run: mvn clean install

    # Chạy test với Maven
    - name: Run tests with Maven
      run: mvn test
